split by probe type (bpf/mod)

diff --git a/kernel-modules/build/build-kos b/kernel-modules/build/build-kos
--- a/kernel-modules/build/build-kos
+++ b/kernel-modules/build/build-kos
@@ -5,108 +5,116 @@ set -euo pipefail
 build_ko() (
     local kernel_version="$1"
     local module_version="$2"
+    local probe_type="$3"
 
-    echo "Building collector module for kernel version ${kernel_version} and module version ${module_version}."
+    if [[ "$probe_type" == "mod" ]]; then
+        echo "Building collector module for kernel version ${kernel_version} and module version ${module_version}."
 
-    mkdir -p /scratch/module-src
-    local module_src_dir="/scratch/module-src/${module_version}"
-    [[ -d "$module_src_dir" ]] || cp -r "/sources/${module_version}" "$module_src_dir"
+        mkdir -p /scratch/module-src
+        local module_src_dir="/scratch/module-src/${module_version}"
+        [[ -d "$module_src_dir" ]] || cp -r "/sources/${module_version}" "$module_src_dir"
 
-    local kernel_src_dir="/scratch/kernel-src/${kernel_version}"
-    if [[ ! -d "$kernel_src_dir" ]]; then
-        rm -rf /scratch/kernel-src/* 2>/dev/null || true
-        mkdir -p "$kernel_src_dir"
-        tar -C "$kernel_src_dir" -xzf "/bundles/bundle-${kernel_version}.tgz"
-    fi
+        local kernel_src_dir="/scratch/kernel-src/${kernel_version}"
+        if [[ ! -d "$kernel_src_dir" ]]; then
+            rm -rf /scratch/kernel-src/* 2>/dev/null || true
+            mkdir -p "$kernel_src_dir"
+            tar -C "$kernel_src_dir" -xzf "/bundles/bundle-${kernel_version}.tgz"
+        fi
 
-    [[ -f "${kernel_src_dir}/BUNDLE_BUILD_DIR" ]] || {
-        echo "No BUNDLE_BUILD_DIR entry found in kernel source bundle!"
-        return 1
-    }
+        [[ -f "${kernel_src_dir}/BUNDLE_BUILD_DIR" ]] || {
+            echo "No BUNDLE_BUILD_DIR entry found in kernel source bundle!"
+            return 1
+        }
 
-    local kernel_build_dir
-    kernel_build_dir="${kernel_src_dir}/$(cat "${kernel_src_dir}/BUNDLE_BUILD_DIR")"
+        local kernel_build_dir
+        kernel_build_dir="${kernel_src_dir}/$(cat "${kernel_src_dir}/BUNDLE_BUILD_DIR")"
 
-    cd "$module_src_dir"
-    KERNELDIR="$kernel_build_dir" make clean
-    KERNELDIR="$kernel_build_dir" make -j 6 all
+        cd "$module_src_dir"
+        KERNELDIR="$kernel_build_dir" make clean
+        KERNELDIR="$kernel_build_dir" make -j 6 all
 
-    collector_ko=collector.ko
-    strip -g "$collector_ko"
+        collector_ko=collector.ko
+        strip -g "$collector_ko"
 
-    [[ -f "${kernel_src_dir}/BUNDLE_UNAME" ]] || {
-        echo "No BUNDLE_UNAME entry found in kernel source bundle!"
-        return 1
-    }
+        [[ -f "${kernel_src_dir}/BUNDLE_UNAME" ]] || {
+            echo "No BUNDLE_UNAME entry found in kernel source bundle!"
+            return 1
+        }
 
-    local kernel_uname
-    kernel_uname="$(cat "${kernel_src_dir}/BUNDLE_UNAME")"
+        local kernel_uname
+        kernel_uname="$(cat "${kernel_src_dir}/BUNDLE_UNAME")"
 
-    ko_version="$(/sbin/modinfo "$collector_ko" | grep vermagic | tr -s " " | cut -d " " -f 2)"
-    if [[ "$ko_version" != "$kernel_uname" ]]; then
-        echo "Corrupted probe, KO_VERSION=$ko_version, KERNEL_VERSION=$kernel_uname" >&2
-        return 1
-    fi
+        ko_version="$(/sbin/modinfo "$collector_ko" | grep vermagic | tr -s " " | cut -d " " -f 2)"
+        if [[ "$ko_version" != "$kernel_uname" ]]; then
+            echo "Corrupted probe, KO_VERSION=$ko_version, KERNEL_VERSION=$kernel_uname" >&2
+            return 1
+        fi
 
-    mkdir -p "/output/${module_version}"
-    gzip -c "$collector_ko" >"/output/${module_version}/collector-${kernel_version}.ko.gz"
-    rm "$collector_ko"
+        mkdir -p "/output/${module_version}"
+        gzip -c "$collector_ko" >"/output/${module_version}/collector-${kernel_version}.ko.gz"
+        rm "$collector_ko"
+    elif [[ "$probe_type" == "bpf" ]]; then
+        # Build eBPF probe, if possible
 
-    # Build eBPF probe, if possible
+        if [[ ! -d "${module_src_dir}/bpf" ]]; then
+            echo "Module version does not support eBPF probe building, skipping ..."
+            return 0
+        fi
 
-    if [[ ! -d "${module_src_dir}/bpf" ]]; then
-        echo "Module version does not support eBPF probe building, skipping ..."
-        return 0
-    fi
+        # Check kernel version >= 4.14
+        kernel_major="$(cat "${kernel_src_dir}/BUNDLE_VERSION")"
+        kernel_minor="$(cat "${kernel_src_dir}/BUNDLE_MAJOR")"
+        kernel_distro="$(cat "${kernel_src_dir}/BUNDLE_DISTRO")"
 
-    # Check kernel version >= 4.14
-    kernel_major="$(cat "${kernel_src_dir}/BUNDLE_VERSION")"
-    kernel_minor="$(cat "${kernel_src_dir}/BUNDLE_MAJOR")"
-    kernel_distro="$(cat "${kernel_src_dir}/BUNDLE_DISTRO")"
+        [[ -n "$kernel_major" && -n "$kernel_minor" ]] || {
+            echo >&2 "Bundle does not contain major/minor version information!"
+            return 1
+        }
 
-    [[ -n "$kernel_major" && -n "$kernel_minor" ]] || {
-        echo >&2 "Bundle does not contain major/minor version information!"
-        return 1
-    }
-
-    # Check if this kernel is from RHEL 7.6+ with backported eBPF support
-    local rhel7_kernel_with_ebpf=false
-    if (( kernel_major == 3 && kernel_minor >= 10 )); then
-        # RHEL 7.6 detection: distro=="redhat" and kernel build id at least 957
-        # Assumption is that RHEL 7.6 will continue to use kernel 3.10
-        if [[ "$kernel_distro" == "redhat" ]]; then
-            # Extract build id: 3.10.0-957.10.1.el7.x86_64 -> 957
-            local rhel_build_id
-            rhel_build_id="$(echo "$kernel_uname" | awk -F'[-.]' '{ print $4 }')"
-            # disable ebpf builds on kernels >= 1062 until ROX-3377 is resolved
-            if (( rhel_build_id >= 957 && rhel_build_id < 1062 )); then
-                echo "Kernel ${kernel_uname} has backported eBPF support"
-                rhel7_kernel_with_ebpf=true
+        # Check if this kernel is from RHEL 7.6+ with backported eBPF support
+        local rhel7_kernel_with_ebpf=false
+        if (( kernel_major == 3 && kernel_minor >= 10 )); then
+            # RHEL 7.6 detection: distro=="redhat" and kernel build id at least 957
+            # Assumption is that RHEL 7.6 will continue to use kernel 3.10
+            if [[ "$kernel_distro" == "redhat" ]]; then
+                # Extract build id: 3.10.0-957.10.1.el7.x86_64 -> 957
+                local rhel_build_id
+                rhel_build_id="$(echo "$kernel_uname" | awk -F'[-.]' '{ print $4 }')"
+                # disable ebpf builds on kernels >= 1062 until ROX-3377 is resolved
+                if (( rhel_build_id >= 957 && rhel_build_id < 1062 )); then
+                    echo "Kernel ${kernel_uname} has backported eBPF support"
+                    rhel7_kernel_with_ebpf=true
+                fi
             fi
         fi
-    fi
 
-    # Check if this module version supports RHEL 7.6 with backported eBPF support
-    if [[ "$rhel7_kernel_with_ebpf" == true ]]; then
-        if ! grep -qRIs "SUPPORTS_RHEL76_EBPF" "${module_src_dir}/bpf/quirks.h"; then
-            echo "Module version ${module_version} does not support eBPF on RHEL 7"
-            return 0
+        # Check if this module version supports RHEL 7.6 with backported eBPF support
+        if [[ "$rhel7_kernel_with_ebpf" == true ]]; then
+            if ! grep -qRIs "SUPPORTS_RHEL76_EBPF" "${module_src_dir}/bpf/quirks.h"; then
+                echo "Module version ${module_version} does not support eBPF on RHEL 7"
+                touch "/output/${module_version}/.collector-ebpf-${kernel_version}.unavail"
+                return 0
+            fi
+
+        # Check kernel version is at least 4.14 (unless RHEL 7.6 kernel detected)
+        else
+            if (( kernel_major < 4 || (kernel_major == 4 && kernel_minor < 14) )); then
+                echo "Kernel version ${kernel_version} does not support eBPF probe building, skipping ..."
+                touch "/output/${module_version}/.collector-ebpf-${kernel_version}.unavail"
+                return 0
+            fi
         fi
 
-    # Check kernel version is at least 4.14 (unless RHEL 7.6 kernel detected)
+        echo "Building collector eBPF probe for kernel version ${kernel_version} and module version ${module_version}."
+        KERNELDIR="$kernel_build_dir" make -j 6 -C bpf
+
+        collector_probe="bpf/probe.o"
+        gzip -c "$collector_probe" >"/output/${module_version}/collector-ebpf-${kernel_version}.o.gz"
+        rm "$collector_probe"
     else
-        if (( kernel_major < 4 || (kernel_major == 4 && kernel_minor < 14) )); then
-            echo "Kernel version ${kernel_version} does not support eBPF probe building, skipping ..."
-            return 0
-        fi
-    fi
-
-    echo "Building collector eBPF probe for kernel version ${kernel_version} and module version ${module_version}."
-    KERNELDIR="$kernel_build_dir" make -j 6 -C bpf
-
-    collector_probe="bpf/probe.o"
-    gzip -c "$collector_probe" >"/output/${module_version}/collector-ebpf-${kernel_version}.o.gz"
-    rm "$collector_probe"
+        echo >&2 "Invalid probe type '${probe_type}'"
+        return 1
+    fo
 )
 
 build_kos() {
