Split by probe type (bpf/mod) and add patch for module version 7c3... (#240)

diff --git a/kernel-modules/build/build-kos b/kernel-modules/build/build-kos
--- a/kernel-modules/build/build-kos
+++ b/kernel-modules/build/build-kos
@@ -5,8 +5,7 @@ set -euo pipefail
 build_ko() (
     local kernel_version="$1"
     local module_version="$2"
-
-    echo "Building collector module for kernel version ${kernel_version} and module version ${module_version}."
+    local probe_type="$3"
 
     mkdir -p /scratch/module-src
     local module_src_dir="/scratch/module-src/${module_version}"
@@ -27,13 +26,6 @@ build_ko() (
     local kernel_build_dir
     kernel_build_dir="${kernel_src_dir}/$(cat "${kernel_src_dir}/BUNDLE_BUILD_DIR")"
 
-    cd "$module_src_dir"
-    KERNELDIR="$kernel_build_dir" make clean
-    KERNELDIR="$kernel_build_dir" make -j 6 all
-
-    collector_ko=collector.ko
-    strip -g "$collector_ko"
-
     [[ -f "${kernel_src_dir}/BUNDLE_UNAME" ]] || {
         echo "No BUNDLE_UNAME entry found in kernel source bundle!"
         return 1
@@ -42,82 +34,101 @@ build_ko() (
     local kernel_uname
     kernel_uname="$(cat "${kernel_src_dir}/BUNDLE_UNAME")"
 
-    ko_version="$(/sbin/modinfo "$collector_ko" | grep vermagic | tr -s " " | cut -d " " -f 2)"
-    if [[ "$ko_version" != "$kernel_uname" ]]; then
-        echo "Corrupted probe, KO_VERSION=$ko_version, KERNEL_VERSION=$kernel_uname" >&2
-        return 1
-    fi
+    cd "$module_src_dir"
 
-    mkdir -p "/output/${module_version}"
-    gzip -c "$collector_ko" >"/output/${module_version}/collector-${kernel_version}.ko.gz"
-    rm "$collector_ko"
+    if [[ "$probe_type" == "mod" ]]; then
+        echo "Building collector module for kernel version ${kernel_version} and module version ${module_version}."
 
-    # Build eBPF probe, if possible
+        KERNELDIR="$kernel_build_dir" make clean
+        KERNELDIR="$kernel_build_dir" make -j 6 all
 
-    if [[ ! -d "${module_src_dir}/bpf" ]]; then
-        echo "Module version does not support eBPF probe building, skipping ..."
-        return 0
-    fi
+        collector_ko=collector.ko
+        strip -g "$collector_ko"
 
-    # Check kernel version >= 4.14
-    kernel_major="$(cat "${kernel_src_dir}/BUNDLE_VERSION")"
-    kernel_minor="$(cat "${kernel_src_dir}/BUNDLE_MAJOR")"
-    kernel_distro="$(cat "${kernel_src_dir}/BUNDLE_DISTRO")"
+        ko_version="$(/sbin/modinfo "$collector_ko" | grep vermagic | tr -s " " | cut -d " " -f 2)"
+        if [[ "$ko_version" != "$kernel_uname" ]]; then
+            echo "Corrupted probe, KO_VERSION=$ko_version, KERNEL_VERSION=$kernel_uname" >&2
+            return 1
+        fi
 
-    [[ -n "$kernel_major" && -n "$kernel_minor" ]] || {
-        echo >&2 "Bundle does not contain major/minor version information!"
-        return 1
-    }
+        mkdir -p "/output/${module_version}"
+        gzip -c "$collector_ko" >"/output/${module_version}/collector-${kernel_version}.ko.gz"
+        rm "$collector_ko"
+    elif [[ "$probe_type" == "bpf" ]]; then
+        # Build eBPF probe, if possible
 
-    # Check if this kernel is from RHEL 7.6+ with backported eBPF support
-    local rhel7_kernel_with_ebpf=false
-    if (( kernel_major == 3 && kernel_minor >= 10 )); then
-        # RHEL 7.6 detection: distro=="redhat" and kernel build id at least 957
-        # Assumption is that RHEL 7.6 will continue to use kernel 3.10
-        if [[ "$kernel_distro" == "redhat" ]]; then
-            # Extract build id: 3.10.0-957.10.1.el7.x86_64 -> 957
-            local rhel_build_id
-            rhel_build_id="$(echo "$kernel_uname" | awk -F'[-.]' '{ print $4 }')"
-            # disable ebpf builds on kernels >= 1062 until ROX-3377 is resolved
-            if (( rhel_build_id >= 957 && rhel_build_id < 1062 )); then
-                echo "Kernel ${kernel_uname} has backported eBPF support"
-                rhel7_kernel_with_ebpf=true
+        if [[ ! -d "${module_src_dir}/bpf" ]]; then
+            echo "Module version does not support eBPF probe building, skipping ..."
+            touch "/output/${module_version}/.collector-ebpf-${kernel_version}.unavail"
+            return 0
+        fi
+
+        # Check kernel version >= 4.14
+        kernel_major="$(cat "${kernel_src_dir}/BUNDLE_VERSION")"
+        kernel_minor="$(cat "${kernel_src_dir}/BUNDLE_MAJOR")"
+        kernel_distro="$(cat "${kernel_src_dir}/BUNDLE_DISTRO")"
+
+        [[ -n "$kernel_major" && -n "$kernel_minor" ]] || {
+            echo >&2 "Bundle does not contain major/minor version information!"
+            return 1
+        }
+
+        # Check if this kernel is from RHEL 7.6+ with backported eBPF support
+        local rhel7_kernel_with_ebpf=false
+        if (( kernel_major == 3 && kernel_minor >= 10 )); then
+            # RHEL 7.6 detection: distro=="redhat" and kernel build id at least 957
+            # Assumption is that RHEL 7.6 will continue to use kernel 3.10
+            if [[ "$kernel_distro" == "redhat" ]]; then
+                # Extract build id: 3.10.0-957.10.1.el7.x86_64 -> 957
+                local rhel_build_id
+                rhel_build_id="$(echo "$kernel_uname" | awk -F'[-.]' '{ print $4 }')"
+                # disable ebpf builds on kernels >= 1062 until ROX-3377 is resolved
+                if (( rhel_build_id >= 957 && rhel_build_id < 1062 )); then
+                    echo "Kernel ${kernel_uname} has backported eBPF support"
+                    rhel7_kernel_with_ebpf=true
+                fi
             fi
         fi
-    fi
 
-    # Check if this module version supports RHEL 7.6 with backported eBPF support
-    if [[ "$rhel7_kernel_with_ebpf" == true ]]; then
-        if ! grep -qRIs "SUPPORTS_RHEL76_EBPF" "${module_src_dir}/bpf/quirks.h"; then
-            echo "Module version ${module_version} does not support eBPF on RHEL 7"
-            return 0
+        # Check if this module version supports RHEL 7.6 with backported eBPF support
+        if [[ "$rhel7_kernel_with_ebpf" == true ]]; then
+            if ! grep -qRIs "SUPPORTS_RHEL76_EBPF" "${module_src_dir}/bpf/quirks.h"; then
+                echo "Module version ${module_version} does not support eBPF on RHEL 7"
+                touch "/output/${module_version}/.collector-ebpf-${kernel_version}.unavail"
+                return 0
+            fi
+
+        # Check kernel version is at least 4.14 (unless RHEL 7.6 kernel detected)
+        else
+            if (( kernel_major < 4 || (kernel_major == 4 && kernel_minor < 14) )); then
+                echo "Kernel version ${kernel_version} does not support eBPF probe building, skipping ..."
+                touch "/output/${module_version}/.collector-ebpf-${kernel_version}.unavail"
+                return 0
+            fi
         fi
 
-    # Check kernel version is at least 4.14 (unless RHEL 7.6 kernel detected)
+        echo "Building collector eBPF probe for kernel version ${kernel_version} and module version ${module_version}."
+        KERNELDIR="$kernel_build_dir" make -j 6 -C bpf
+
+        collector_probe="bpf/probe.o"
+        gzip -c "$collector_probe" >"/output/${module_version}/collector-ebpf-${kernel_version}.o.gz"
+        rm "$collector_probe"
     else
-        if (( kernel_major < 4 || (kernel_major == 4 && kernel_minor < 14) )); then
-            echo "Kernel version ${kernel_version} does not support eBPF probe building, skipping ..."
-            return 0
-        fi
+        echo >&2 "Invalid probe type '${probe_type}'"
+        return 1
     fi
-
-    echo "Building collector eBPF probe for kernel version ${kernel_version} and module version ${module_version}."
-    KERNELDIR="$kernel_build_dir" make -j 6 -C bpf
-
-    collector_probe="bpf/probe.o"
-    gzip -c "$collector_probe" >"/output/${module_version}/collector-ebpf-${kernel_version}.o.gz"
-    rm "$collector_probe"
 )
 
 build_kos() {
     while read -a line || [[ "${#line[@]}" -gt 0 ]]; do
         local kernel_version="${line[0]}"
         local module_version="${line[1]}"
+        local probe_type="${line[2]}"
 
-        if ! build_ko "$kernel_version" "$module_version"; then
-            echo >&2 "Failed to build module version ${module_version} for kernel ${kernel_version}"
+        if ! build_ko "$kernel_version" "$module_version" "${probe_type}"; then
+            echo >&2 "Failed to build "${probe_type}" probe version ${module_version} for kernel ${kernel_version}"
             if [[ -n "${FAILURE_LOG_FILE:-}" ]]; then
-                echo >>"${FAILURE_LOG_FILE}" "${kernel_version} ${module_version}"
+                echo >>"${FAILURE_LOG_FILE}" "${kernel_version} ${module_version} ${probe_type}"
             fi
         fi
     done
