Added instruction to pre-commit error

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -8,7 +8,11 @@ fi
 
 # Check staged scripts formatting
 if command -v shfmt --version >/dev/null; then
-	git diff --name-only --cached --relative | grep -E '\.sh$$' | xargs shfmt -d || exit $?
+	if ! git diff --name-only --cached --relative | grep -E '\.sh$$|^githooks/' | xargs shfmt -d; then
+		echo "Format errors found! Run 'make shfmt-format' in order to fix them."
+		echo "Use the '--no-verify' flag in order to bypass the pre-commit check altogether."
+		exit $?
+	fi
 fi
 
 # Validate CircleCI configuration if it was modified and the CLI is available
