Slight improvement to pre-commit hook

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,3 +1,7 @@
 #!/bin/sh
 
-exec make -C collector check
+if ! make -C collector check; then
+	echo "Format errors found! Run 'make -C collector format' in order to fix them."
+	echo "Use the '--no-verify' flag in order to bypass the pre-commit check altogether."
+	exit 1
+fi
