keep building images in spite of failures

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -613,15 +613,6 @@ jobs:
     - gcloud-init
 
     - run:
-        name: Test for build failures
-        command: |
-          if ls "${WORKSPACE_ROOT}/ko-build/build-output/FAILURES-"* 2>/dev/null; then
-            echo >&2 "Compilation failed for some kernel/module version combinations!"
-            cat >&2 2>/dev/null "${WORKSPACE_ROOT}/ko-build/build-output/FAILURES-"*
-            exit 1
-          fi
-
-    - run:
         name: Copying Kernel modules build output
         command: |
           mkdir -p "${SOURCE_ROOT}/kernel-modules/container/kernel-modules"
@@ -720,10 +711,16 @@ jobs:
       - gcloud-init
 
       - run:
+          name: Save failures file
+          command: |
+            mkdir /tmp/failures
+            mv "${WORKSPACE_ROOT}/ko-build/build-output/FAILURES"-* /tmp/failures 2>/dev/null || true
+
+      - run:
           name: Uploading Kernel modules
           command: |
             extra_args=()
-            if [[ "$CIRCLE_BRANCH" != "master" ]]; then
+            if [[ "$CIRCLE_BRANCH" != "master" && -z "$CIRCLE_TAG" ]]; then
               extra_args+=(-n)
             fi
 
@@ -735,6 +732,16 @@ jobs:
           name: Sanity check
           command:
             gsutil ls "${COLLECTOR_MODULES_BUCKET}/${MODULE_VERSION}/"
+
+      - run:
+          name: Test for build failures
+          command: |
+            if ls /tmp/failures/FAILURES-* 2>/dev/null; then
+              echo >&2 "Compilation failed for some kernel/module version combinations!"
+              cat >&2 2>/dev/null /tmp/failures/FAILURES-*
+              exit 1
+            fi
+
 
   integration-test-local:
     machine: true
