Addressed PR review comments

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -799,16 +799,15 @@ jobs:
         command: |
           make -C "${SOURCE_ROOT}" unittest "USE_VALGRIND=$VALGRIND_UNIT_TESTS" 2>&1 | tee "$UNITTEST_OUTPUT_FILE"
           if [[ "$VALGRIND_UNIT_TESTS" == "true" ]]; then
-            max_allowed_valgrind_errors=0
             valgrind_summary_lines="$({ grep 'ERROR SUMMARY' "$UNITTEST_OUTPUT_FILE" || true ; } | wc -l)"
             if (( valgrind_summary_lines == 0 )); then
               echo "Error: Valgrind summary not found"
               exit 2
             fi
             valgrind_errors="$(grep 'ERROR SUMMARY' "$UNITTEST_OUTPUT_FILE" | awk '{print $7}')"
-            if (( valgrind_errors > max_allowed_valgrind_errors ))
+            if (( valgrind_errors > 0 ))
             then
-              echo "Too many Valgrind errors. Valgrind errors: $valgrind_errors. Maximum Valgrind errors allowed: $max_allowed_valgrind_errors."
+              echo "Found $valgrind_errors Valgrind errors"
               exit 3
             fi
           fi
@@ -844,18 +843,17 @@ jobs:
     - run:
         name: Run RHEL collector unit tests
         command: |
-          make -C "${SOURCE_ROOT}" unittest-rhel USE_VALGRIND=$VALGRIND_UNIT_TESTS 2>&1 | tee $UNITTEST_OUTPUT_FILE
-          if [ $VALGRIND_UNIT_TESTS == "true" ]; then
-            max_allowed_valgrind_errors=0
-            valgrind_summary_lines=`(grep ERROR\ SUMMARY $UNITTEST_OUTPUT_FILE || true) | wc -l`
-            if [ $valgrind_summary_lines -eq 0 ]; then
+          make -C "${SOURCE_ROOT}" unittest-rhel "USE_VALGRIND=$VALGRIND_UNIT_TESTS" 2>&1 | tee "$UNITTEST_OUTPUT_FILE"
+          if [[ "$VALGRIND_UNIT_TESTS" == "true" ]]; then
+            valgrind_summary_lines="$({ grep 'ERROR SUMMARY' "$UNITTEST_OUTPUT_FILE" || true ; } | wc -l)"
+            if (( valgrind_summary_lines == 0 )); then
               echo "Error: Valgrind summary not found"
               exit 2
             fi
-            valgrind_errors=`grep ERROR\ SUMMARY $UNITTEST_OUTPUT_FILE | awk '{print $7}'`
-            if [ $valgrind_errors -gt $max_allowed_valgrind_errors ]
+            valgrind_errors="$(grep 'ERROR SUMMARY' "$UNITTEST_OUTPUT_FILE" | awk '{print $7}')"
+            if (( valgrind_errors > 0 ))
             then
-              echo "Too many Valgrind errors. Valgrind errors: $valgrind_errors. Maximum Valgrind errors allowed: $max_allowed_valgrind_errors."
+              echo "Found $valgrind_errors Valgrind errors"
               exit 3
             fi
           fi
@@ -1269,7 +1267,7 @@ jobs:
           do
             echo "Checking $file for Valgrind errors"
             valgrind_summary="$(grep 'ERROR SUMMARY' "$file" || true)"
-            valgrind_summary_lines=`(grep ERROR\ SUMMARY $file || true) | wc -l`
+            valgrind_summary_lines="$({ grep 'ERROR SUMMARY' $file || true ; } | wc -l)"
             if [ $valgrind_summary_lines -eq 1 ]; then
               valgrind_errors=`echo $valgrind_summary | awk '{print $7}'`
               if [[ $valgrind_errors -gt $max_allowed_valgrind_errors ]]; then
@@ -1371,7 +1369,7 @@ jobs:
     - run:
         name: "Check Valgrind errors"
         command: |
-          if [ $VALGRIND_INTEGRATION_TESTS == "false" ]; then
+          if [[ "$VALGRIND_INTEGRATION_TESTS" != "true" ]]; then
             echo "Not using Valgrind. Not checking for Valgrind errors"
             exit 0
           fi
@@ -1381,8 +1379,8 @@ jobs:
           for file in "$log_dir"/*-collector.log
           do
             echo "Checking $file for Valgrind errors"
-            valgrind_summary=`grep ERROR\ SUMMARY $file || true`
-            valgrind_summary_lines=`(grep ERROR\ SUMMARY $file || true) | wc -l`
+            valgrind_summary="$(grep 'ERROR SUMMARY' "$file" || true)"
+            valgrind_summary_lines="$({ grep 'ERROR SUMMARY' $file || true ; } | wc -l)"
             if [ $valgrind_summary_lines -eq 1 ]; then
               valgrind_errors=`echo $valgrind_summary | awk '{print $7}'`
               if [[ $valgrind_errors -gt $max_allowed_valgrind_errors ]]; then
