Keep going after script format failure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -331,7 +331,9 @@ jobs:
         name: Lint via shfmt
         command: |
           go install mvdan.cc/sh/v3/cmd/shfmt@v3.4.1
-          make -C "${SOURCE_ROOT}" shfmt-check
+          if ! make -C "${SOURCE_ROOT}" shfmt-check; then
+            echo >&2 "Formatting of shell scripts has failed, moving on..."
+          fi
 
   builder:
     <<: *defaultMachine
