Rudi gcos test (#138)
* try to boot gcp node another way for gcos test

* remove tabs

* guess and check cci

* more guess and check for cci

* scale back google storage bucket assumptions

* add SOURCE_ROOT wd

* move randomly

* try to surface error code

* more circle experiments

* try bucket more

* more test circleci perms fix

* add diagnostics

* try to pull docker image to see auth error

* install docker

* separate commands to allow for new group permissions

* add docker login

* adjust docker pull placement after push

* begin integration test

* add golang dist and fix typo

* adjust tests

* fix typo

* fix path

* create /go directory

* fix go dep

* move repo to GOPATH

* add missing -p to mkdir

* add snapshot- to COLLECTOR_TAG

* make tests show fail in red circleci with 'set -e'

* save gcp log as artifact and add another set -e for increased test sensitivity

* fix syntax error

* use /tmp for artifact scratch dir

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,38 @@
 version: 2.1
 
+setupGCP: &setupGCP
+  run:
+    name: Setup GCP env
+    command: |
+      which gcloud
+      which gsutil
+      gsutil ver
+      gsutil ver -l | grep crcmod
+      gcloud version
+      cat ~/.boto || true
+      echo '[Credentials]' >~/.boto
+      echo 'gs_service_key_file = /tmp/gcp.json' >>~/.boto
+      echo $GOOGLE_CREDENTIALS_CIRCLECI_COLLECTOR > /tmp/gcp.json
+      gcloud auth activate-service-account --key-file /tmp/gcp.json
+      gcloud config set project stackrox-ci
+      gcloud config set compute/region us-central1
+      gcloud config unset compute/zone
+      gcloud config set core/disable_prompts True
+      gcloud auth list
+      gsutil ls gs://collector-build-cache/ || echo "ERROR: Could not ls bucket"
+createGCP: &createGCP
+  run:
+    name: Create GCP VM
+    command: |
+      $SOURCE_ROOT/.circleci/create-gcp-vm.sh "$DOCKER_USER" "$DOCKER_PASS" "$SOURCE_ROOT"
+    background: false
+teardownGCP: &teardownGCP
+  run:
+    name: Tear down GCP VM
+    command: |
+      gcloud compute instances delete "collector-nb-${CIRCLE_BUILD_NUM}"
+    when: always
+    background: false
 commands:
   init:
     steps:
@@ -9,7 +42,7 @@ commands:
         name: Set up environment
         command: |
           cat >>"$BASH_ENV" \<<-EOF
-          	export WORKSPACE_ROOT="${HOME}/workspace"
+            export WORKSPACE_ROOT="${HOME}/workspace"
           EOF
           [[ -f ~/workspace/shared-env ]] && cat ~/workspace/shared-env >>"$BASH_ENV"
 
@@ -22,15 +55,13 @@ commands:
           if [[ -z "$ROX_CI_IMAGE" ]]; then
             pip install -U crcmod google_compute_engine
           fi
-          gcloud auth activate-service-account --key-file <(echo "$GOOGLE_CREDENTIALS_CIRCLECI_COLLECTOR")
-          gcloud auth list
+    - *setupGCP
 
   docker-login:
     steps:
     - run:
         name: Login to Docker Hub
         command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
-
 jobs:
   init:
     docker:
@@ -45,15 +76,15 @@ jobs:
         name: Set up shared environment
         command: |
           cat >~/workspace/shared-env \<<-"EOF"
-          	export GOPATH="${WORKSPACE_ROOT}/go"
-          	export SOURCE_ROOT="${GOPATH}/src/github.com/stackrox/collector"
+            export GOPATH="${WORKSPACE_ROOT}/go"
+            export SOURCE_ROOT="${GOPATH}/src/github.com/stackrox/collector"
             export COLLECTOR_SOURCE_ROOT="${SOURCE_ROOT}/collector"
-          	export PATH="${PATH}:${GOPATH}/bin:${WORKSPACE_ROOT}/bin"
+            export PATH="${PATH}:${GOPATH}/bin:${WORKSPACE_ROOT}/bin"
           EOF
 
           COLLECTOR_VERSION="$(make -s -C ~/workspace/go/src/github.com/stackrox/collector/collector tag)"
           cat >>~/workspace/shared-env \<<-EOF
-          	export COLLECTOR_VERSION="$COLLECTOR_VERSION"
+            export COLLECTOR_VERSION="$COLLECTOR_VERSION"
           EOF
 
     - persist_to_workspace:
@@ -119,10 +150,10 @@ jobs:
           version="$(basename "${versions[0]}")"
           MODULE_VERSION="${version%.tgz}"
           cat >>"${WORKSPACE_ROOT}/shared-env" \<<-EOF
-          	export MODULE_VERSION="${MODULE_VERSION}"
+            export MODULE_VERSION="${MODULE_VERSION}"
           EOF
           cat >>"$BASH_ENV" \<<-EOF
-          	export MODULE_VERSION="${MODULE_VERSION}"
+            export MODULE_VERSION="${MODULE_VERSION}"
           EOF
           echo "Building modules for module version $version"
 
@@ -513,6 +544,7 @@ jobs:
     - init
     - docker-login
     - gcloud-init
+    - *createGCP
 
     - run:
         name: Copying Kernel modules build output
@@ -579,19 +611,44 @@ jobs:
           docker images | grep collector | grep "$COLLECTOR_VERSION"
 
     - run:
+        name: Check remote host GCP kernel version
+        command: |
+          gcloud compute ssh "collector-nb-${CIRCLE_BUILD_NUM}" --command "uname -r && uname -a"
+    - run:
         name: Push images
         command: |
           if [[ $CIRCLE_BRANCH = master || -n $CIRCLE_TAG ]]; then
             echo Pushing release images
-            docker push "stackrox/collector:${COLLECTOR_VERSION}"
+            IMAGE_COLLECTOR="stackrox/collector:${COLLECTOR_VERSION}"
+            IMAGE_KERNEL_MODULES="stackrox/kernel-modules:${MODULE_VERSION}"
+            docker push "${IMAGE_COLLECTOR}"
             echo "Pushing kernel modules"
-            docker push "stackrox/kernel-modules:${MODULE_VERSION}"
+            docker push "${IMAGE_KERNEL_MODULES}"
           else
             echo Pushing snapshot images
-            docker push "stackrox/collector:snapshot-${COLLECTOR_VERSION}"
+            IMAGE_COLLECTOR="stackrox/collector:snapshot-${COLLECTOR_VERSION}"
+            IMAGE_KERNEL_MODULES="stackrox/kernel-modules:snapshot-${COLLECTOR_VERSION}"
+            docker push "${IMAGE_COLLECTOR}"
             echo "Pushing kernel modules"
-            docker push "stackrox/kernel-modules:snapshot-${COLLECTOR_VERSION}"
+            docker push "${IMAGE_KERNEL_MODULES}"
           fi
+          set -e
+          gcloud compute ssh "collector-nb-${CIRCLE_BUILD_NUM}" --command "docker pull ${IMAGE_COLLECTOR}"
+          gcloud compute ssh "collector-nb-${CIRCLE_BUILD_NUM}" --command "docker pull ${IMAGE_KERNEL_MODULES}"
+          gcloud compute ssh "collector-nb-${CIRCLE_BUILD_NUM}" --command "cd /home/circleci/collector/.circleci && bash run-integration-tests ${COLLECTOR_VERSION}"
+          gcloud compute scp "collector-nb-${CIRCLE_BUILD_NUM}:/go/src/github.com/stackrox/collector/collector/integration-test-report.xml" /tmp/integration-test-report-gcp.xml
+          gcloud compute scp "collector-nb-${CIRCLE_BUILD_NUM}:/go/src/github.com/stackrox/collector/integration-tests/grpc_server.logs" /tmp/grpc_server_gcp.logs
+          gcloud compute scp "collector-nb-${CIRCLE_BUILD_NUM}:/go/src/github.com/stackrox/collector/integration-tests/collector.logs" /tmp/collector_gcp.logs
+    - store_artifacts:
+        path: /tmp/integration-test-report-gcp.xml
+        destination: integration-test-report-gcp.xml/tmp
+    - store_artifacts:
+        path: /tmp/grpc_server_gcp.logs
+        destination: grpc_server_gcp.logs
+    - store_artifacts:
+        path: /tmp/collector_gcp.logs
+        destination: collector_gcp.logs
+    - *teardownGCP
 
     - run:
         name: Integration tests
