Add automated shell script formatting (#536)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -331,6 +331,14 @@ jobs:
         command: |
            make -C "${COLLECTOR_SOURCE_ROOT}" check
 
+    - run:
+        name: Lint via shfmt
+        command: |
+          go install mvdan.cc/sh/v3/cmd/shfmt@v3.4.1
+          if ! make -C "${SOURCE_ROOT}" shfmt-check; then
+            echo >&2 "Formatting of shell scripts has failed, moving on..."
+          fi
+
   builder:
     <<: *defaultMachine
     resource_class: large
diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -6,6 +6,14 @@ if ! make -C collector check-staged; then
 	exit 1
 fi
 
+# Check staged scripts formatting
+if command -v shfmt --version >/dev/null; then
+	if ! git diff --name-only --cached --relative | grep -E '\.sh$$|^githooks/' | xargs shfmt -d; then
+		echo "Format errors found! Run 'make shfmt-format' in order to fix them."
+		echo "Use the '--no-verify' flag in order to bypass the pre-commit check altogether."
+	fi
+fi
+
 # Validate CircleCI configuration if it was modified and the CLI is available
 if command -v circleci >/dev/null && git diff --name-only --cached | grep -qE '^\.circleci/config\.yml$'; then
 	echo "Validating CircleCI configuration..."
