prod version

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -167,7 +167,7 @@ jobs:
 
   prepare-kernels:
     docker:
-    - image: docker.io/stackrox/apollo-ci:snapshot-collector-0.2.7-4-g09c8a87c35
+    - image: docker.io/stackrox/apollo-ci:snapshot-collector-0.2.7-6-g808141948a
       auth:
         username: $DOCKER_USER
         password: $DOCKER_PASS
@@ -748,9 +748,38 @@ jobs:
           echo "Pushing collector rhel latest image"
           docker push "stackrox/collector-rhel:${COLLECTOR_VERSION}-latest"
 
+  kernel-module-build-failures-check:
+    docker:
+      - image: docker.io/stackrox/apollo-ci:snapshot-collector-0.2.7-6-g808141948a
+        auth:
+          username: $DOCKER_USER
+          password: $DOCKER_PASS
+      environment:
+        ROX_CI_IMAGE: "true"
+
+    working_directory: ~/workspace
+
+    steps:
+      - initcommand
+
+      - run:
+          name: Save failures files
+          command: |
+            mkdir /tmp/failures
+            mv "${WORKSPACE_ROOT}/ko-build/build-output/FAILURES"-* /tmp/failures 2>/dev/null || true
+
+      - run:
+          name: Test for build failures
+          command: |
+            if ls /tmp/failures/FAILURES-* 2>/dev/null; then
+              echo >&2 "Compilation failed for some kernel/module version combinations!"
+              cat >&2 2>/dev/null /tmp/failures/FAILURES-*
+              exit 1
+            fi
+
   upload-modules:
     docker:
-    - image: docker.io/stackrox/apollo-ci:snapshot-collector-0.2.7-4-g09c8a87c35
+    - image: docker.io/stackrox/apollo-ci:snapshot-collector-0.2.7-6-g808141948a
       auth:
         username: $DOCKER_USER
         password: $DOCKER_PASS
@@ -764,10 +793,9 @@ jobs:
       - gcloud-init
 
       - run:
-          name: Save failures file
+          name: Remove failures file
           command: |
-            mkdir /tmp/failures
-            mv "${WORKSPACE_ROOT}/ko-build/build-output/FAILURES"-* /tmp/failures 2>/dev/null || true
+            rm "${WORKSPACE_ROOT}/ko-build/build-output/FAILURES"-* 2>/dev/null || true
 
       - run:
           name: Uploading Kernel modules
@@ -781,20 +809,11 @@ jobs:
               "${WORKSPACE_ROOT}/ko-build/build-output/" \
               "${COLLECTOR_MODULES_BUCKET}/"
 
-
       - run:
           name: Sanity check
           command:
             gsutil ls "${COLLECTOR_MODULES_BUCKET}/${MODULE_VERSION}/"
 
-      - run:
-          name: Test for build failures
-          command: |
-            if ls /tmp/failures/FAILURES-* 2>/dev/null; then
-              echo >&2 "Compilation failed for some kernel/module version combinations!"
-              cat >&2 2>/dev/null /tmp/failures/FAILURES-*
-              exit 1
-            fi
 
   integration-test-local:
     parameters:
@@ -976,14 +995,14 @@ jobs:
 
   update-support-packages:
     docker:
-      - image: docker.io/stackrox/apollo-ci:snapshot-collector-0.2.7-4-g09c8a87c35
+      - image: docker.io/stackrox/apollo-ci:snapshot-collector-0.2.7-6-g808141948a
         auth:
           username: $DOCKER_USER
           password: $DOCKER_PASS
 
     environment:
       - DOWNLOAD_BASE_URL: "https://install.stackrox.io"
-      - RELATIVE_PATH: "collector-test-xkl5x1/support-packages"
+      - RELATIVE_PATH: "collector/support-packages"
       - GCLOUD_BUCKET: "gs://sr-roxc"
 
     working_directory: ~/workspace
@@ -1023,7 +1042,7 @@ jobs:
           name: Generate collector -> rox version map
           command: |
             "${SUPPORT_PKG_SRC_ROOT}/01-collector-to-rox-version-map.py" \
-              "${SOURCE_ROOT}/TEST_RELEASED_VERSIONS" \
+              "${SOURCE_ROOT}/RELEASED_VERSIONS" \
               /tmp/support-packages/metadata
 
       - run:
@@ -1067,8 +1086,10 @@ jobs:
       - run:
           name: Delete old files
           command: |
-            echo gsutil -m rsync -n -r -d /tmp/support-packages/output "$GCLOUD_TARGET"
-            sleep 120
+            # Sanity check. If for some reason GCLOUD_TARGET is malformed, we risk deleting the
+            # entire `sr-roxc` bucket (!!!). Hence have a hardcoded check for the path looking
+            # valid.
+            [[ "$GCLOUD_TARGET" =~ ^gs://[^/]+/.*collector.*/.*support-packages.*$ ]]
             gsutil -m rsync -n -r -d /tmp/support-packages/output "$GCLOUD_TARGET"
 
   reload-released-images:
@@ -1149,248 +1170,257 @@ workflows:
         filters:
           tags:
             only: /.*/
-#    - builder:
-#        requires:
-#        - initjob
-#        filters:
-#          tags:
-#            only: /.*/
-#    - collector:
-#        requires:
-#        - builder
-#        filters:
-#          tags:
-#            only: /.*/
-#    - builder-rhel:
-#        requires:
-#        - initjob
-#        filters:
-#          tags:
-#            only: /.*/
-#    - collector-rhel:
-#        requires:
-#        - builder-rhel
-#        filters:
-#          tags:
-#            only: /.*/
-#    - prepare-kernels:
-#        requires:
-#        - initjob
-#        filters:
-#          tags:
-#            only: /.*/
-#    - kernels:
-#        requires:
-#        - prepare-kernels
-#        filters:
-#          tags:
-#            only: /.*/
-#    - upload-modules:
-#        requires:
-#          - kernels
-#        filters:
-#          tags:
-#            only: /.*/
-#    - images:
-#        requires:
-#        - collector
-#        - collector-rhel
-#        - kernels
-#        filters:
-#          tags:
-#            only: /.*/
-#    - integration-test-local:
-#        requires:
-#        - images
-#        - upload-modules
-#        filters:
-#          tags:
-#            only: /.*/
-#    - integration-test-local:
-#        name: integration-test-local-rhel
-#        vm-config: rhel
-#        use-rhel: true
-#        requires:
-#        - images
-#        - upload-modules
-#        filters:
-#          tags:
-#            only: /.*/
-#    # TODO(rc) Enabled but bootstrap.sh forces fallback to kernel-module (ROX-2583)
-#    - integration-test:
-#        name: test-ebpf-coreos-stable
-#        collection_method: ebpf
-#        vm_type: coreos
-#        image_family: coreos-stable
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    - integration-test:
-#        name: test-module-coreos-stable
-#        collection_method: module
-#        vm_type: coreos
-#        image_family: coreos-stable
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    ## TODO(rc) Enable after fixing `Kernel panic - not syncing: softlockup: hung tasks` (ROX-3179)
-#    #- integration-test:
-#    #    name: test-ebpf-cos-stable
-#    #    collection_method: ebpf
-#    #    vm_type: cos
-#    #    image_family: cos-stable
-#    #    requires:
-#    #    - images
-#    #    - integration-test-local
-#    #    filters:
-#    #      tags:
-#    #        only: /.*/
-#    - integration-test:
-#        name: test-ebpf-cos-69-lts
-#        collection_method: ebpf
-#        vm_type: cos
-#        image_family: cos-69-lts
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    - integration-test:
-#        name: test-ebpf-cos-73-lts
-#        collection_method: ebpf
-#        vm_type: cos
-#        image_family: cos-73-lts
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    - integration-test:
-#        name: test-ebpf-rhel-7
-#        collection_method: ebpf
-#        vm_type: rhel
-#        image_family: rhel-7
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    # TODO(rc) Enabled but bootstrap.sh forces fallback to kernel-module (ROX-3377)
-#    - integration-test:
-#        name: test-module-rhel-7
-#        collection_method: module
-#        vm_type: rhel
-#        image_family: rhel-7
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    - integration-test:
-#        name: test-ebpf-rhel-8
-#        collection_method: ebpf
-#        vm_type: rhel
-#        image_family: rhel-8
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    - integration-test:
-#        name: test-module-rhel-8
-#        collection_method: module
-#        vm_type: rhel
-#        image_family: rhel-8
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    ## TODO(rc) Enable after fixing `Kernel panic - not syncing: softlockup: hung tasks`
-#    #- integration-test:
-#    #    name: test-ebpf-ubuntu-1804-lts
-#    #    collection_method: ebpf
-#    #    vm_type: ubuntu-os
-#    #    image_family: ubuntu-1804-lts
-#    #    requires:
-#    #    - images
-#    #    - integration-test-local
-#    #    filters:
-#    #      tags:
-#    #        only: /.*/
-#    - integration-test:
-#        name: test-module-ubuntu-1804-lts
-#        collection_method: module
-#        vm_type: ubuntu-os
-#        image_family: ubuntu-1804-lts
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#    ## TODO(rc) Enable after fixing `Kernel panic - not syncing: softlockup: hung tasks`
-#    #- integration-test:
-#    #    name: test-ebpf-ubuntu-1904
-#    #    collection_method: ebpf
-#    #    vm_type: ubuntu-os
-#    #    image_family: ubuntu-1904
-#    #    requires:
-#    #    - images
-#    #    - integration-test-local
-#    #    filters:
-#    #      tags:
-#    #        only: /.*/
-#    - integration-test:
-#        name: test-module-ubuntu-1904
-#        collection_method: module
-#        vm_type: ubuntu-os
-#        image_family: ubuntu-1904
-#        requires:
-#        - images
-#        - integration-test-local
-#        filters:
-#          tags:
-#            only: /.*/
-#
-#    - integration-test-data:
-#       requires:
-#       - test-module-coreos-stable
-#       - test-ebpf-coreos-stable
-#       #- test-ebpf-cos-stable
-#       - test-ebpf-cos-69-lts
-#       - test-ebpf-cos-73-lts
-#       - test-module-rhel-7
-#       - test-ebpf-rhel-7
-#       - test-module-rhel-8
-#       - test-ebpf-rhel-8
-#       - test-module-ubuntu-1804-lts
-#       #- test-ebpf-ubuntu-1804-lts
-#       - test-module-ubuntu-1904
-#       #- test-ebpf-ubuntu-1904
-#       filters:
-#         tags:
-#           only: /.*/
-#    - reload-released-images:
-#        context: docker-io-and-stackrox-io-push
-#        requires:
-#        - images
-#        filters:
-#          branches:
-#            only: master
-    - update-support-packages:
+    - builder:
+        requires:
+        - initjob
+        filters:
+          tags:
+            only: /.*/
+    - collector:
+        requires:
+        - builder
+        filters:
+          tags:
+            only: /.*/
+    - builder-rhel:
+        requires:
+        - initjob
+        filters:
+          tags:
+            only: /.*/
+    - collector-rhel:
+        requires:
+        - builder-rhel
+        filters:
+          tags:
+            only: /.*/
+    - prepare-kernels:
+        requires:
+        - initjob
+        filters:
+          tags:
+            only: /.*/
+    - kernels:
+        requires:
+        - prepare-kernels
+        filters:
+          tags:
+            only: /.*/
+    - upload-modules:
+        requires:
+          - kernels
+        filters:
+          tags:
+            only: /.*/
+    - kernel-module-build-failures-check:
+        requires:
+          - kernels
+        filters:
+          tags:
+            only: /.*/
+    - images:
+        requires:
+        - collector
+        - collector-rhel
+        - kernels
+        filters:
+          tags:
+            only: /.*/
+    - integration-test-local:
+        requires:
+        - images
+        - upload-modules
+        filters:
+          tags:
+            only: /.*/
+    - integration-test-local:
+        name: integration-test-local-rhel
+        vm-config: rhel
+        use-rhel: true
+        requires:
+        - images
+        - upload-modules
+        filters:
+          tags:
+            only: /.*/
+    # TODO(rc) Enabled but bootstrap.sh forces fallback to kernel-module (ROX-2583)
+    - integration-test:
+        name: test-ebpf-coreos-stable
+        collection_method: ebpf
+        vm_type: coreos
+        image_family: coreos-stable
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    - integration-test:
+        name: test-module-coreos-stable
+        collection_method: module
+        vm_type: coreos
+        image_family: coreos-stable
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    ## TODO(rc) Enable after fixing `Kernel panic - not syncing: softlockup: hung tasks` (ROX-3179)
+    #- integration-test:
+    #    name: test-ebpf-cos-stable
+    #    collection_method: ebpf
+    #    vm_type: cos
+    #    image_family: cos-stable
+    #    requires:
+    #    - images
+    #    - integration-test-local
+    #    filters:
+    #      tags:
+    #        only: /.*/
+    - integration-test:
+        name: test-ebpf-cos-69-lts
+        collection_method: ebpf
+        vm_type: cos
+        image_family: cos-69-lts
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    - integration-test:
+        name: test-ebpf-cos-73-lts
+        collection_method: ebpf
+        vm_type: cos
+        image_family: cos-73-lts
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    - integration-test:
+        name: test-ebpf-rhel-7
+        collection_method: ebpf
+        vm_type: rhel
+        image_family: rhel-7
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    # TODO(rc) Enabled but bootstrap.sh forces fallback to kernel-module (ROX-3377)
+    - integration-test:
+        name: test-module-rhel-7
+        collection_method: module
+        vm_type: rhel
+        image_family: rhel-7
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    - integration-test:
+        name: test-ebpf-rhel-8
+        collection_method: ebpf
+        vm_type: rhel
+        image_family: rhel-8
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    - integration-test:
+        name: test-module-rhel-8
+        collection_method: module
+        vm_type: rhel
+        image_family: rhel-8
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    ## TODO(rc) Enable after fixing `Kernel panic - not syncing: softlockup: hung tasks`
+    #- integration-test:
+    #    name: test-ebpf-ubuntu-1804-lts
+    #    collection_method: ebpf
+    #    vm_type: ubuntu-os
+    #    image_family: ubuntu-1804-lts
+    #    requires:
+    #    - images
+    #    - integration-test-local
+    #    filters:
+    #      tags:
+    #        only: /.*/
+    - integration-test:
+        name: test-module-ubuntu-1804-lts
+        collection_method: module
+        vm_type: ubuntu-os
+        image_family: ubuntu-1804-lts
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+    ## TODO(rc) Enable after fixing `Kernel panic - not syncing: softlockup: hung tasks`
+    #- integration-test:
+    #    name: test-ebpf-ubuntu-1904
+    #    collection_method: ebpf
+    #    vm_type: ubuntu-os
+    #    image_family: ubuntu-1904
+    #    requires:
+    #    - images
+    #    - integration-test-local
+    #    filters:
+    #      tags:
+    #        only: /.*/
+    - integration-test:
+        name: test-module-ubuntu-1904
+        collection_method: module
+        vm_type: ubuntu-os
+        image_family: ubuntu-1904
+        requires:
+        - images
+        - integration-test-local
+        filters:
+          tags:
+            only: /.*/
+
+    - integration-test-data:
+       requires:
+       - test-module-coreos-stable
+       - test-ebpf-coreos-stable
+       #- test-ebpf-cos-stable
+       - test-ebpf-cos-69-lts
+       - test-ebpf-cos-73-lts
+       - test-module-rhel-7
+       - test-ebpf-rhel-7
+       - test-module-rhel-8
+       - test-ebpf-rhel-8
+       - test-module-ubuntu-1804-lts
+       #- test-ebpf-ubuntu-1804-lts
+       - test-module-ubuntu-1904
+       #- test-ebpf-ubuntu-1904
+       filters:
+         tags:
+           only: /.*/
+    - reload-released-images:
         context: docker-io-and-stackrox-io-push
         requires:
-          - initjob
+        - images
+        filters:
+          branches:
+            only: master
+    - update-support-packages:
+        context: docker-io-and-stackrox-io-push
+        filters:
+          branches:
+            only: master
+        requires:
+          - upload-modules
