Rollback some changes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1269,6 +1269,30 @@ jobs:
 
           "$SOURCE_ROOT/.circleci/build-dockerized-image.sh"
 
+          # Check the required module has been built
+          if [[ "${COLLECTION_METHOD}" == "module" ]]; then
+            test_pattern="${KERNEL_VERSION}"
+            if [[ "<< parameters.image_family >>" == "ubuntu-2004-lts" ]]; then
+              test_pattern="${KERNEL_VERSION}~20\.04"
+            elif [[ "<< parameters.image_family >>" == "ubuntu-1604-lts" ]]; then
+              test_pattern="${KERNEL_VERSION}~16\.04"
+            fi
+
+            echo "${test_pattern}"
+            if ! gcloud compute ssh --ssh-key-file="${GCP_SSH_KEY_FILE}" "${GCP_VM_USER}@${GCLOUD_INSTANCE}" --command "docker run --rm kernel-builder 'find /kernel-modules -name \"*\.ko\.gz\"'" | grep -q "${test_pattern}\.ko\.gz"; then
+              echo >&2 "Required kernel module for ${KERNEL_VERSION} has not been built"
+              exit 1
+            fi
+          fi
+
+          # Build and tag the test image
+          docker build \
+            --tag "${COLLECTOR_REPO}:${CIRCLE_BUILD_NUM}" \
+            --build-arg COLLECTOR_TAG="${COLLECTOR_TAG}-slim" \
+            /home/${GCP_VM_USER}/ctx/collector/kernel-modules/dockerized/tests
+
+          docker push "${COLLECTOR_REPO}:${CIRCLE_BUILD_NUM}"
+
     - run:
         name: "Running integration tests"
         no_output_timeout: 45m
